name: Release to github packages

on:
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: read
  packages: write

jobs:
  call-workflow-ci-build-publish-lib:
    uses: felleslosninger/github-workflows/.github/workflows/ci-build-publish-lib.yml@main
    with:
      java-version: 17
      package-version: ${{ github.event.release.tag_name }}
      deployment-repository: ${{ github.repository }}
      sbom-path: ./
    secrets: inherit
