name: Pull request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - main

permissions:
  contents: read
  packages: read

jobs:
  pull-request-checks:
    uses: felleslosninger/github-workflows/.github/workflows/ci-maven-build-lib.yml@main
    with:
      java-version: 17
    secrets: inherit
